export { default as Slider } from "./Slider";
export { default as HowTo } from "./HowTo";
export { default as Tabs } from "./Tabs";
export { default as Card } from "./Card";
export { default as CallUs } from "./CallUs";
export { default as Footer } from "./Footer";
export { default as Order } from "./Order";
export { default as MobileApp } from "./MobileApp";
export { default as HowToGet } from "./HowToGet";
